spring:
  rabbitmq:
    host: 106.53.147.3
    port: 5672
    username: admin
    password: 823113
  cloud:
    nacos:
      server-addr: 106.53.147.3:8848
      config:
        namespace: ${spring.profiles.active}
        group: xuecheng-plus-project
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: logging-${spring.profiles.active}.yaml
            group: xuecheng-plus-common
            refresh: true
  profiles:
    active: dev
