### 课程查询列表接口
POST {{content_host}}/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "courseName": "java",
  "audiStatus": "202004",
  "publishStatus": "203001"
}
### 课程分类查询接口
GET {{content_host}}/course-category/tree-nodes
Content-Type: application/json